/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visual;

import javax.swing.JTable;
import proyecto.Producto;

/**
 *
 * @author angel
 */
public class PanelPrecio1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form PanelPrecio1
     */
    public PanelPrecio1() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //codigo a mano
    int productosamostrarmaximo;
    int productosamostrarminimo;
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtmax = new javax.swing.JTextField();
        jtmin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtprecio = new javax.swing.JTable();
        btnSalirPrecio = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado por Precio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Entre $");

        jtmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtmaxKeyReleased(evt);
            }
        });

        jtmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtminKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("y");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-search-64.png"))); // NOI18N

        jtprecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Categoria", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtprecio);

        btnSalirPrecio.setText("Cerrar");
        btnSalirPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPrecioActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtmax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtmin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSalirPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtmin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtmax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btnSalirPrecio)
                        .addGap(35, 35, 35))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jtmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSalirPrecio)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirPrecioActionPerformed
       this.dispose();
       
    }//GEN-LAST:event_btnSalirPrecioActionPerformed

    private void jtminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtminKeyReleased
    
        productosamostrarminimo = 0; 
        
    if (!jtmin.getText().trim().isEmpty()) {
        int preciomin = Integer.parseInt(jtmin.getText().trim());
        for (Producto producto : VentanaPrincipal.productos) {
            double precio = producto.getPrecio();
            if (preciomin <= precio) { 
                productosamostrarminimo++; 
            }            
        }
    }
    mostrarSegunPreciosElejidos();
    }//GEN-LAST:event_jtminKeyReleased

    private void jtmaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtmaxKeyReleased
         productosamostrarmaximo = 0; 
         
    if (!jtmax.getText().trim().isEmpty()) {
        int preciomax = Integer.parseInt(jtmax.getText().trim());
        for (Producto producto : VentanaPrincipal.productos) {
            double precio = producto.getPrecio();
            if (precio <= preciomax) {  
                productosamostrarmaximo++; 
            }           
        }
    }
    mostrarSegunPreciosElejidos();
    }//GEN-LAST:event_jtmaxKeyReleased
    public void mostrarSegunPreciosElejidos(){
    String[][] Tablas;
    String[] columnas = {"Codigo", "Descripcion" ,"Precio", "Categoria" ,"Stock"};
    
    //si los dos estan vacios
    if (jtmin.getText().trim().isEmpty() && jtmax.getText().trim().isEmpty()) {
        Tablas = new String[VentanaPrincipal.productos.size()][5];
        int f = 0;
        for (Producto producto : VentanaPrincipal.productos) {                      
            Tablas[f][0] = String.valueOf(producto.getCodigo());
            Tablas[f][1] = producto.getDescripcion();
            Tablas[f][2] = String.valueOf(producto.getPrecio());
            Tablas[f][3] = producto.getCategoria();
            Tablas[f][4] = String.valueOf(producto.getStock());
            f++;
        }
        JTable tabla = new JTable(Tablas, columnas);        
        jtprecio.setModel(tabla.getModel()); 
    }
    //solo mostrar minimo    
    else if (!jtmin.getText().trim().isEmpty() && jtmax.getText().trim().isEmpty()) {
        int numerominimo = Integer.parseInt(jtmin.getText().trim());
        Tablas = new String[productosamostrarminimo][5];
        int f = 0;
        for (Producto producto : VentanaPrincipal.productos) {
            if (numerominimo <= producto.getPrecio()) {
                Tablas[f][0] = String.valueOf(producto.getCodigo());
                Tablas[f][1] = producto.getDescripcion();
                Tablas[f][2] = String.valueOf(producto.getPrecio());
                Tablas[f][3] = producto.getCategoria();
                Tablas[f][4] = String.valueOf(producto.getStock());
                f++;
            }
        }
        JTable tabla = new JTable(Tablas, columnas);        
        jtprecio.setModel(tabla.getModel());   
    }
    //solo mostrar máximo
    else if (jtmin.getText().trim().isEmpty() && !jtmax.getText().trim().isEmpty()) {
        int numeromaximo = Integer.parseInt(jtmax.getText().trim());
        Tablas = new String[productosamostrarmaximo][5];
        int f = 0;
        for (Producto producto : VentanaPrincipal.productos) {
            if (producto.getPrecio() <= numeromaximo) {
                Tablas[f][0] = String.valueOf(producto.getCodigo());
                Tablas[f][1] = producto.getDescripcion();
                Tablas[f][2] = String.valueOf(producto.getPrecio());
                Tablas[f][3] = producto.getCategoria();
                Tablas[f][4] = String.valueOf(producto.getStock());
                f++;
            }
        }
        JTable tabla = new JTable(Tablas, columnas);        
        jtprecio.setModel(tabla.getModel());
    }
    //mostrar minimo y maximo
    else {
        int numerominimo = Integer.parseInt(jtmin.getText().trim());
        int numeromaximo = Integer.parseInt(jtmax.getText().trim());
        
        int count = 0;
        for (Producto producto : VentanaPrincipal.productos) {
            if (numerominimo <= producto.getPrecio() && producto.getPrecio() <= numeromaximo) {
                count++;
            }
        }
        
        Tablas = new String[count][5];
        int f = 0;
        for (Producto producto : VentanaPrincipal.productos) {
            if (numerominimo <= producto.getPrecio() && producto.getPrecio() <= numeromaximo) {
                Tablas[f][0] = String.valueOf(producto.getCodigo());
                Tablas[f][1] = producto.getDescripcion();
                Tablas[f][2] = String.valueOf(producto.getPrecio());
                Tablas[f][3] = producto.getCategoria();
                Tablas[f][4] = String.valueOf(producto.getStock());
                f++;
            }
        }
        JTable tabla = new JTable(Tablas, columnas);        
        jtprecio.setModel(tabla.getModel());   
    }
}


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalirPrecio;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtmax;
    private javax.swing.JTextField jtmin;
    private javax.swing.JTable jtprecio;
    // End of variables declaration//GEN-END:variables
}
